version: "3.9"

name: wiremock-khepri
services:
  mongo-khepri:
    container_name: mongodb-khepri
    platform: linux/arm64
    image: mongo:3.6-jessie
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - database-data:/data/db
    networks:
      - khepri-network
    command: mongod --verbose --smallfiles  --dbpath=/data/db
  wiremock:
    container_name: wiremock-khepri
    platform: linux/arm64
    build:
      context: .
      dockerfile: multi-stage.dockerfile
    networks:
      - khepri-network
    depends_on:
      mongo-khepri:
        condition: service_healthy

volumes:
  database-data:

networks:
  khepri-network:
    driver: bridge
